/** Chuỗi giao diện tiếng Việt — tập trung một chỗ. */
export const t = {
  appName: 'Dự chi hàng tháng',
  auth: {
    email: 'Email',
    error: 'Đăng nhập thất bại. Kiểm tra email/mật khẩu.',
    errorGoogle: 'Đăng nhập Google thất bại. Vui lòng thử lại.',
    googleSignIn: 'Đăng nhập với Google',
    password: 'Mật khẩu',
    signIn: 'Đăng nhập',
    signUp: 'Tạo tài khoản',
    switchToSignIn: 'Đã có tài khoản? Đăng nhập',
    switchToSignUp: 'Chưa có tài khoản? Đăng ký',
  },
  budget: {
    actuals: 'Chi thực tế',
    add: 'Thêm dự chi',
    addActual: 'Ghi chi thực tế',
    amount: 'Số tiền (VND)',
    category: 'Phân loại',
    delete: 'Xóa',
    edit: 'Sửa',
    remaining: 'Còn lại trong tháng',
    title: 'Khoản dự chi',
    titleLabel: 'Tên khoản',
    validFrom: 'Áp dụng từ tháng',
    validTo: 'Đến tháng (để trống = vô hạn)',
  },
  common: {
    cancel: 'Hủy',
    edit: 'Sửa',
    loading: 'Đang tải…',
    month: 'Tháng',
    note: 'Ghi chú',
    period: 'Kỳ áp dụng',
    save: 'Lưu',
    status: 'Trạng thái',
    visible: 'Hiển thị',
  },
  home: {
    actualSpent: 'Chi thực tế',
    actualSurplus: 'Dư sau chi thực tế',
    income: 'Thu nhập',
    plannedBudget: 'Dự chi (kế hoạch)',
    plannedSurplus: 'Dư sau dự chi (kế hoạch)',
    subtitle: 'Theo dõi dự chi, thu nhập và tiết kiệm (VND).',
    thisMonth: 'Tháng này',
    title: 'Tổng quan',
  },
  income: {
    add: 'Thêm kỳ thu nhập',
    amount: 'Số tiền (VND)',
    label: 'Mô tả',
    title: 'Thu nhập theo kỳ',
    validFrom: 'Từ tháng',
    validTo: 'Đến tháng (để trống = hiện tại)',
  },
  nav: {
    budget: 'Dự chi',
    home: 'Tổng quan',
    income: 'Thu nhập',
    login: 'Đăng nhập',
    logout: 'Đăng xuất',
    settings: 'Danh mục',
    stats: 'Thống kê',
  },
  settings: {
    add: 'Thêm danh mục',
    archived: 'Đã ẩn',
    hide: 'Ẩn',
    name: 'Tên',
    show: 'Hiện',
    title: 'Danh mục phân loại',
  },
  stats: {
    accumulated: 'Tích lũy',
    actual: 'Chi thực tế',
    actualSurplus: 'Tiết kiệm (thực tế)',
    income: 'Thu nhập',
    month: 'Tháng',
    monthly: 'Theo tháng',
    planned: 'Dự chi',
    plannedSurplus: 'Tiết kiệm (kế hoạch)',
    savingsAccumulatedMonthly: 'Tích lũy tiết kiệm (Từng tháng)',
    subtitle: 'Từ tháng hiện tại đến hết năm, cộng thêm 12 tháng năm sau.',
    tabDetail: 'Bảng chi tiết',
    tabSavings: 'Tiết kiệm',
    tabsDescription: 'Gộp bảng chi tiết và tiết kiệm.',
    tabsTitle: 'Chi tiết',
    title: 'Thống kê theo tháng',
  },
} as const
