export const t = {
  appName: 'Monthly Budget',
  auth: {
    errorGoogle: 'Không thể đăng nhập bằng Google. Thử lại sau.',
    googleSignIn: 'Tiếp tục với Google',
  },
  budget: {
    actualAmountQuickPickRemainingTitle: 'Phần còn lại chưa chi trong tháng đã chọn (dự chi trừ tổng đã ghi).',
    actualExpenseLineDeleteDialogTitle: 'Xóa dòng chi thực tế?',
    actualLinesEmpty: 'Chưa có dòng chi thực tế trong tháng đã chọn.',
    actualLinesHeading: 'Các khoản đã ghi',
    actualPeriodHint: 'Chỉ ghi chi thực tế cho tháng hiện tại của khoản dự chi còn hiệu lực.',
    actualPeriodInactiveLocked: 'Chỉ ghi chi thực tế trong kỳ áp dụng của khoản này.',
    actuals: 'Chi thực tế',
    actualSpentMonthReadOnlyHint: 'Chỉ ghi chi thực tế cho tháng hiện tại.',
    add: 'Thêm khoản dự chi',
    addActual: 'Ghi chi thực tế',
    addActualAction: 'Ghi chi thực tế',
    addActualBody: 'Số tiền này được trừ khỏi cột Còn lại của đúng khoản và đúng tháng.',
    addActualContext: 'ghi số tiền đã chi cho khoản này',
    amount: 'Số tiền (VND)',
    category: 'Phân loại',
    createdAt: 'Ngày ghi',
    delete: 'Xóa',
    deleteAction: 'Xóa khoản dự chi',
    deleteDialogP2:
      'Khoản dự chi này sẽ không còn trong danh sách dự chi. Các mục chi thực tế đã ghi trước đó vẫn lưu trong tài khoản nhưng không còn liên kết với tên khoản này, nên tổng quan và thống kê có thể khác trước khi xóa.',
    deleteDialogTitle: 'Xóa khoản dự chi?',
    dialogP1: 'Tạo một khoản dự chi theo từng kỳ áp dụng.',
    dialogP2c: 'Bỏ trống tháng kết thúc nếu khoản dự chi này còn dùng cho các tháng sau.',
    edit: 'Sửa',
    editAction: 'Sửa khoản dự chi',
    emptyList: 'Chưa có khoản dự chi.',
    fieldValidFrom: 'Bắt đầu từ tháng',
    fieldValidTo: 'Đến tháng',
    pageDetail: 'Mỗi khoản có danh mục và thời gian áp dụng riêng.',
    pageLead: 'Lập kế hoạch chi từng khoản theo từng tháng.',
    periodColumn: 'Kỳ',
    periodColumnHint: 'Kỳ áp dụng mà khoản này được tính vào tổng dự chi.',
    periodEndedLocked: 'Kỳ đã kết thúc — không sửa, xóa hay ghi chi thực tế.',
    remaining: 'Còn lại (VND)',
    remainingHint: 'Số tiền còn lại sau khi dự chi trong tháng đang xem.',
    saveActualAction: 'Thêm chi thực tế',
    termRemaining: 'Còn lại',
    title: 'Dự chi',
    titleLabel: 'Tên khoản',
    validFrom: 'Từ tháng',
    validFromCreateHint: 'Chỉ cho phép tạo khoản từ tháng hiện tại trở đi.',
    validTo: 'Đến tháng (tùy chọn)',
    validToHint: 'Có thể trùng tháng với từ tháng hoặc chọn tháng sau.',
  },
  common: {
    amountQuickPickHint: 'Chạm một mức để điền nhanh. Gợi ý thay đổi theo số đang nhập (ví dụ 25 → 25.000, 250.000…).',
    amountQuickPickLabel: 'Gợi ý nhập nhanh',
    back: 'Quay lại',
    cancel: 'Hủy',
    close: 'Đóng',
    delete: 'Xóa',
    edit: 'Sửa',
    loading: 'Đang tải…',
    month: 'Tháng',
    monthsUnit: 'tháng',
    moreInfo: 'Mô tả thêm',
    noItemsInSelectedYear: 'Không có mục nào trong năm đã chọn.',
    noScopeMonths: 'Không có tháng nào trong phạm vi này',
    note: 'Ghi chú',
    orSeparator: 'hoặc',
    period: 'Kỳ áp dụng',
    periodEndedLocked: 'Kỳ đã kết thúc — không sửa hoặc xóa để giữ nguyên dữ liệu cũ.',
    pickMonth: 'Chọn tháng',
    save: 'Lưu',
    selectPlaceholder: 'Chọn',
    status: 'Trạng thái',
    theme: 'Giao diện',
    themeDark: 'Tối',
    themeLight: 'Sáng',
    themeSystem: 'Theo hệ thống',
    visible: 'Hiển thị',
    year: 'Năm',
  },
  home: {
    actualSavingsHint: 'Cộng dồn phần dư thực tế từ các tháng trước đến tháng này.',
    actualSavingsToDatePlusSurplusLine: '+ Dư thực tế {{monthLabel}}: {{amount}}',
    actualSavingsToDatePriorLine: 'Tích lũy thực tế đến hết {{monthLabel}}: {{amount}}',
    actualSpent: 'Thực chi',
    actualSpentHint: 'Tổng số tiền thực tế đã chi trong tháng này.',
    actualSurplus: 'Dư thực tế',
    actualSurplusHint: 'Thu nhập trừ thực chi trong tháng đang xem.',
    breakdownEmpty: 'Chưa có mục nào trong tháng này.',
    income: 'Thu nhập của tháng',
    incomeHint: 'Tổng các kỳ thu nhập còn hiệu lực trong tháng này.',
    nextMonth: 'Tháng sau',
    nextMonthPlannedAccumulationHint:
      'Phần tích lũy đến hết tháng đang xem lấy theo thực tế; cộng dồn thêm phần dư theo dự tính của tháng sau.',
    nextMonthPlannedOnlyNote:
      'Tháng chưa diễn ra — chỉ hiển thị thu nhập và chỉ số theo dự tính; thực chi và dư thực tế sẽ có sau khi tháng đó bắt đầu.',
    orphanedBudgetActual: 'Khoản dự chi đã xóa',
    plannedBudget: 'Dự chi',
    plannedBudgetHint: 'Tổng các khoản dự chi có hiệu lực trong tháng này.',
    plannedSavingsHint: 'Cộng dồn phần dư theo kế hoạch từ các tháng trước đến tháng này.',
    plannedSavingsToDatePlusSurplusLine: '+ Dư theo dự tính {{monthLabel}}: {{amount}}',
    plannedSavingsToDatePriorLine: 'Tích lũy đến hết {{monthLabel}}: {{amount}}',
    plannedSurplus: 'Dư theo dự tính',
    plannedSurplusHint: 'Số tiền còn lại sau khi dự chi trong tháng này.',
    savingsToDateActual: 'Dư tích lũy theo thực tế',
    savingsToDatePlanned: 'Dư tích lũy theo dự tính',
    subtitle:
      'Xem nhanh thu nhập, dự chi, thực chi và phần dư theo kế hoạch cũng như theo thực tế (kể cả tích lũy đến tháng đang xem).',
    subtitleDetail: 'Dữ liệu lấy từ các mục Thu nhập, Dự chi và Chi thực tế.',
    thisMonth: 'Tháng này',
    title: 'Tổng quan',
  },
  income: {
    add: 'Thêm kỳ thu nhập',
    amount: 'Số tiền (VND)',
    deleteAction: 'Xóa kỳ thu nhập',
    deleteDialogP2:
      'Kỳ thu nhập sẽ không còn trong danh sách kỳ thu nhập. Các tháng trong quá khứ từng dùng mức thu này có thể hiển thị khác trên tổng quan và thống kê.',
    deleteDialogTitle: 'Xóa kỳ thu nhập?',
    dialogP1: 'Tạo một mức thu nhập theo tháng. Khi thu nhập đổi, thêm kỳ mới thay vì sửa lại từng tháng.',
    dialogP2c: 'Bỏ trống tháng kết thúc nếu mức thu này còn dùng cho các tháng sau.',
    editAction: 'Sửa kỳ thu nhập',
    editTitle: 'Sửa kỳ thu nhập',
    emptyList: 'Chưa có kỳ thu nhập nào.',
    fieldValidFrom: 'Từ tháng',
    fieldValidTo: 'Đến tháng',
    label: 'Tên kỳ thu nhập',
    pageDetail: 'Khi thu nhập thay đổi, tạo kỳ mới với giai đoạn áp dụng phù hợp.',
    pageLead: 'Khai báo các mức thu nhập áp dụng theo từng giai đoạn.',
    title: 'Thu nhập theo kỳ',
    validFrom: 'Từ tháng',
    validTo: 'Đến tháng (tùy chọn)',
    validToHint: 'Bỏ trống nếu tiếp tục áp dụng từ tháng bắt đầu về sau.',
  },
  nav: {
    account: 'Tài khoản',
    budget: 'Dự chi',
    drawerTitle: 'Menu điều hướng',
    home: 'Tổng quan',
    income: 'Thu nhập',
    logout: 'Đăng xuất',
    openMenu: 'Mở menu điều hướng',
    settings: 'Phân loại',
    stats: 'Thống kê',
  },
  settings: {
    add: 'Thêm danh mục',
    archived: 'Đã ẩn',
    dialogP1: 'Đặt tên ngắn, dễ hiểu khi tạo khoản dự chi. Không dùng ký tự đặc biệt.',
    emptyList: 'Chưa có danh mục nào.',
    hide: 'Ẩn',
    hideAction: 'Ẩn danh mục',
    name: 'Tên',
    pageDetail: 'Ẩn danh mục khi không dùng nữa; các khoản dự chi cũ vẫn giữ nguyên.',
    pageLead: 'Tạo nhóm để phân loại các khoản dự chi.',
    show: 'Hiện',
    showAction: 'Hiện danh mục',
    title: 'Phân loại',
  },
  stats: {
    accumulated: 'Tích lũy (dư theo dự)',
    actual: 'Thực chi',
    actualAccumulatedColumnHint: 'Cộng dồn phần dư thực tế (thu nhập trừ thực chi) qua từng tháng.',
    actualAccumulatedMonthly: 'Dư tích lũy theo thực tế',
    actualAvgTagline: 'Tính theo các tháng trong bảng.',
    actualColumnHint: 'Tổng số tiền đã ghi thực tế trong tháng đó.',
    actualMonthlySurplus: 'Dư thực tế',
    actualMonthlySurplusColumnHint: 'Thu nhập trừ thực chi trong tháng đó.',
    actualSurplus: 'Dư thực tế bình quân',
    actualSurplusHint: 'Bình quân mỗi tháng: thu nhập trừ thực chi.',
    averagePerMonth: 'Trung bình mỗi tháng',
    collapseMonthBreakdown: 'Thu gọn chi tiết',
    collapseYearGroup: 'Thu gọn các tháng',
    expandMonthBreakdown: 'Xem thêm chi tiết',
    expandYearGroup: 'Mở các tháng',
    income: 'Thu nhập',
    incomeColumnHint: 'Tổng các kỳ thu nhập còn hiệu lực trong tháng đó.',
    month: 'Tháng',
    monthly: 'Theo tháng',
    pageDetail: 'Hiển thị đủ các tháng của năm hiện tại và năm sau; các tháng được gom theo từng năm.',
    pageLead: 'Xem thu, chi và phần dư theo từng tháng.',
    planned: 'Dự chi (tổng)',
    plannedAvgTagline: 'Tính theo các tháng trong bảng.',
    plannedHintColumn: 'Tổng các khoản dự chi có hiệu lực trong tháng đó.',
    plannedSurplus: 'Dư theo kế hoạch',
    plannedSurplusColumnHint: 'Thu nhập trừ tổng dự chi trong tháng đó.',
    plannedSurplusHint: 'Bình quân mỗi tháng: thu nhập trừ dự chi.',
    savingsAccumulatedColumnHint: 'Cộng dồn phần dư theo kế hoạch qua từng tháng.',
    savingsAccumulatedMonthly: 'Tích lũy theo dự tính',
    tabDetail: 'Chi tiết theo tháng',
    tabDetailTooltip: 'Thu nhập, dự chi, thực chi, phần dư kế hoạch và dư thực tế từng tháng.',
    tabSavings: 'Tích lũy theo tháng',
    tabSavingsTooltip: 'Phần dư theo kế hoạch và theo thực tế, cùng tích lũy tương ứng qua các tháng.',
    title: 'Thống kê',
  },
  validation: {
    actualSpentMonthCurrentOnly: 'Chỉ được ghi chi thực tế cho tháng hiện tại.',
    amountAtLeastOne: 'Nhập số tiền từ 1.000 VND trở lên.',
    amountNotNegative: 'Số tiền không được âm.',
    categoryRequired: 'Chọn phân loại.',
    labelRequired: 'Nhập tên kỳ thu nhập.',
    monthFormat: 'Chọn tháng hợp lệ.',
    nameRequired: 'Nhập tên danh mục.',
    noteRequired: 'Nhập ghi chú.',
    titleRequired: 'Nhập tên khoản.',
    validFromNotBeforeCurrent: 'Khi tạo mới, chỉ chọn từ tháng hiện tại trở đi.',
    validToBeforeFrom: 'Tháng kết thúc không được trước tháng bắt đầu.',
  },
} as const

export function actualExpenseLineDeleteDialogP1(formattedAmount: string, monthLabel: string) {
  return `Bạn sắp xóa dòng chi ${formattedAmount} (${monthLabel}). Thao tác này không thể hoàn tác.`
}

export function budgetDeleteDialogP1(title: string) {
  return `Bạn sắp xóa khoản dự chi “${title}”. Thao tác này không thể hoàn tác.`
}

export function incomeDeleteDialogP1(label: string) {
  return `Bạn sắp xóa kỳ thu nhập “${label}”. Thao tác này không thể hoàn tác.`
}
